#!/usr/bin/env bash
set -Eeuo pipefail

if [[ ${1-} != disk ]]; then exit 2; fi

printf '%s\n' query >>"${DISK_FIXTURE_LIFECYCLE_LOG:?}"
mode=$(<"${DISK_FIXTURE_LIFECYCLE_MODE:?}")
case "$mode" in
  nonzero)
    exit 7
    ;;
  hold)
    printf '%s\n' held >"${DISK_FIXTURE_LIFECYCLE_HELD:?}"
    printf '%s\n' '{"icon":"O","value":"old","tooltip":"old","class":"active"}'
    if [[ -n ${DISK_FIXTURE_LIFECYCLE_OLD_OUTPUT:-} ]]; then
      printf '%s\n' old >"$DISK_FIXTURE_LIFECYCLE_OLD_OUTPUT"
    fi
    while [[ ! -e ${DISK_FIXTURE_LIFECYCLE_RELEASE:?} ]]; do sleep 0.01; done
    ;;
  success)
    printf '%s\n' '{"icon":"N","value":"new","tooltip":"new","class":"active"}'
    ;;
  *)
    exit 3
    ;;
esac
