[global]
   allow insecure wide links = yes
   workgroup = WORKGROUP
   server role = standalone server
   security = user
   map to guest = never
   interfaces = lo virbr0
   bind interfaces only = yes
   smb ports = 445
   disable netbios = yes
   server min protocol = SMB3_00
   hosts allow = 127.0.0.1 192.168.122.0/24
   logging = systemd
   log level = 1

[multidev]
   follow symlinks = yes
   wide links = yes
   path = /home/a.simard@multidev.local/gits/multidev
   browseable = yes
   read only = no
   guest ok = no
   valid users = +samba-multidev
   acl allow execute always = yes
   create mask = 0664
   directory mask = 0775
   store dos attributes = yes
