[mgr]
show_hidden=true
linemode="size_and_mtime"

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = 'nvim %*',   block = true, for = "windows" },
]
admin = [
  { run = 'gsudo %*', orphan = true, for = "windows" },
]

[open]
prepend_rules = [
  { name = "*", use = [ "edit", "admin" ] },
]

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git"
url   = "*/"
run   = "git"
group = "git"
