# App-specific tweaks
source = ~/.config/hypr/adopted/apps/1password.conf
source = ~/.config/hypr/adopted/apps/bitwarden.conf
source = ~/.config/hypr/adopted/apps/browser.conf
source = ~/.config/hypr/adopted/apps/hyprshot.conf
source = ~/.config/hypr/adopted/apps/jetbrains.conf
source = ~/.config/hypr/adopted/apps/localsend.conf
source = ~/.config/hypr/adopted/apps/pip.conf
source = ~/.config/hypr/adopted/apps/qemu.conf
source = ~/.config/hypr/adopted/apps/retroarch.conf
source = ~/.config/hypr/adopted/apps/steam.conf
source = ~/.config/hypr/adopted/apps/geforce.conf
source = ~/.config/hypr/adopted/apps/moonlight.conf
source = ~/.config/hypr/adopted/apps/system.conf
source = ~/.config/hypr/adopted/apps/telegram.conf
source = ~/.config/hypr/adopted/apps/terminals.conf
source = ~/.config/hypr/adopted/apps/walker.conf
source = ~/.config/hypr/adopted/apps/webcam-overlay.conf
