return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "vim",
      "lua",
      "vimdoc",
      "html",
      "css",
      "bash",
      "json",
      "yaml",
      "toml",
      "nu",
      "ini",
      "dockerfile",
      "markdown",
      "markdown_inline",
      "cpp",
      "go",
      "latex",
      "pascal",
      "php",
      "rust",
      "sql",
      "lua",
      "javascript",
      "typescript",
      "nginx",
      "python",
      "java",
      "c",
      "c_sharp",
      "comment",
    },
  },
  -- might be optional
  dependencies = {
    { "nushell/tree-sitter-nu", build = ":TSUpdate" },
  },
}
