format = """
$os\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hg_state\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$netns\
$shell
"""
# palette = 'onedark' 

[aws]
format = '[$symbol($profile)(\($region\))(\[$duration)]($style)\] '
symbol = " "

[azure]
format = '[$symbol($subscription)]($style) '

[battery]
format = '[$symbol$percentage]($style) '

[buf]
format = '[$symbol($version)]($style) '
symbol = " "

[bun]
format = '[$symbol($version)]($style) '
symbol = " "

[c]
format = '[$symbol($version(-$name))]($style) '
symbol = " "

[cmake]
format = '[$symbol($version)]($style) '
symbol = " "

[cmd_duration]
format = '[⏱ $duration]($style) '

[cobol]
format = '[$symbol($version)]($style) '

[conda]
format = '[$symbol$environment]($style) '
symbol = " "

[container]
format = '[$symbol \[$name]($style)\]'

[cpp]
format = '[$symbol($version(-$name))]($style) '
symbol = " "

[crystal]
format = '[$symbol($version)]($style) '
symbol = " "

[daml]
format = '[$symbol($version)]($style) '

[dart]
format = '[$symbol($version)]($style) '
symbol = " "

[deno]
format = '[$symbol($version)]($style) '
symbol = " "

[directory]
truncation_length = 5
read_only = " 󰌾"
# truncation_symbol = "…"

[direnv]
format = '[$symbol$loaded/$allowed]($style) '

[docker_context]
format = '[$symbol$context]($style) '
symbol = " "

[dotnet]
format = '[$symbol($version)(🎯 $tfm)]($style) '

[elixir]
format = '[$symbol($version \(OTP $otp_version\))]($style) '
symbol = " "

[elm]
format = '[$symbol($version)]($style) '
symbol = " "

[erlang]
format = '[$symbol($version)]($style) '

[fennel]
format = '[$symbol($version)]($style) '
symbol = " "

[fortran]
format = '[$symbol($version)]($style) '
symbol = " "

[fossil_branch]
format = '[$symbol$branch]($style) '
symbol = " "

[fossil_metrics]
format = '[+$added]($added_style)\[[-$deleted]($deleted_style)\] '

[gcloud]
format = '$symbol'#'[$symbol$account(@$domain)(\($region\))]($style) '
symbol = " "

[git_branch]
format = '[$symbol$branch]($style) '
symbol = " "

[git_commit]
format = '[\($hash$tag\)]($style) '
tag_symbol = '  '

[git_metrics]
format = '[+$added]($added_style)\[[-$deleted]($deleted_style)\] '

[git_state]
format = '[$state ($progress_current/$progress_total)]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style)) '

[gleam]
format = '[$symbol($version)]($style) '

[golang]
format = '[$symbol($version)]($style) '
symbol = " "

[gradle]
format = '[$symbol($version)]($style) '
symbol = " "

[guix_shell]
format = '[$symbol]($style) '
symbol = " "

[haskell]
format = '[$symbol($version)]($style) '
symbol = " "

[haxe]
format = '[$symbol($version)]($style) '
symbol = " "

[helm]
format = '[$symbol($version)]($style) '

[hg_branch]
format = '[$symbol$branch]($style) '
symbol = " "

[hostname]
format = '[$ssh_symbol($hostname)]($style) '
ssh_symbol = " "

[java]
format = '[$symbol($version)]($style) '
symbol = " "

[jobs]
format = '[$symbol$number]($style) '

[julia]
format = '[$symbol($version)]($style) '
symbol = " "

[kotlin]
format = '[$symbol($version)]($style) '
symbol = " "

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '

[localip]
format = '[$localipv4]($style) '

[lua]
format = '[$symbol($version)]($style) '
symbol = " "

[memory_usage]
format = '$symbol[$ram( | $swap)]($style) '
symbol = "󰍛 "

[meson]
format = '[$symbol$project]($style) '
symbol = "󰔷 "

[mise]
format = '[$symbol$health]($style) '

[mojo]
format = '[$symbol($version)]($style) '

[nats]
format = '[$symbol$name]($style) '

[netns]
format = '[$symbol \[$name]($style)\]'

[nim]
format = '[$symbol($version)]($style) '
symbol = "󰆥 "

[nix_shell]
format = '[$symbol$state( \($name\))]($style) '
symbol = " "

[nodejs]
format = '[$symbol($version)]($style) '
symbol = " "

[ocaml]
format = '[$symbol($version)(\($switch_indicator$switch_name\))]($style) '
symbol = " "

[odin]
format = '[$symbol($version )]($style) '

[opa]
format = '[$symbol($version)]($style) '

[openstack]
format = '[$symbol$cloud(\($project\))]($style) '

[os]
disabled = false
format = '[$symbol]($style) '

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
format = '[$symbol$version]($style) '
symbol = "󰏗 "

[perl]
format = '[$symbol($version)]($style) '
symbol = " "

[php]
format = '[$symbol($version)]($style) '
symbol = " "

[pijul_channel]
format = '[$symbol$channel]($style) '
symbol = " "

[pixi]
format = '[$symbol$version( $environment)]($style) '
symbol = "󰏗 "

[pulumi]
format = '[$symbol$stack]($style) '

[purescript]
format = '[$symbol($version)]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = " "

[quarto]
format = '[$symbol($version)]($style) '

[raku]
format = '[$symbol($version-$vm_version)]($style) '

[red]
format = '[$symbol($version)]($style) '

[rlang]
format = '[$symbol($version)]($style) '
symbol = "󰟔 "

[ruby]
format = '[$symbol($version)]($style) '
symbol = " "

[rust]
format = '[$symbol($version)]($style) '
symbol = "󱘗 "

[scala]
format = '[$symbol($version)]($style) '
symbol = " "

[shell]
nu_indicator = ''
powershell_indicator = ' '
bash_indicator = '\$'
zsh_indicator = '%'
format = '[$indicator]($style) '
disabled = false

[singularity]
format = '[$symbol\[$env]($style) '

[solidity]
format = '[$symbol($version)]($style) '

[spack]
format = '[$symbol$environment]($style) '

[status]
format = '[$symbol$status]($style) '
symbol = " "

[sudo]
format = '[as $symbol]($style) '

[swift]
format = '[$symbol($version)]($style) '
symbol = " "

[terraform]
format = '[$symbol$workspace]($style) '

[time]
format = '[$time]($style) '

[typst]
format = '[$symbol($version)]($style) '

[username]
format = '[$user]($style) '

[vagrant]
format = '[$symbol($version)]($style) '

[vcsh]
format = 'vcsh [$symbol$repo]($style) '

[vlang]
format = '[$symbol($version)]($style) '

[xmake]
format = '[$symbol($version)]($style) '
symbol = " "

[zig]
format = '[$symbol($version)]($style) '
symbol = " "

