# export FZF_DEFAULT_OPTS="--style full --tmux --preview='bat --color=always --line-range:500 {}'" 
export FZF_DEFAULT_OPTS="--style full --preview='~/.config/fzf/fzf-preview.sh {}'" 
export FZF_DEFAULT_COMMAND="fd --type f"
export BAT_THEME="OneHalfDark"
export ZSH="/usr/share/oh-my-zsh"
export MANPAGER="sh -c 'awk '\''{ gsub(/\x1B\[[0-9;]*m/, \"\", \$0); gsub(/.\x08/, \"\", \$0); print }'\'' | bat -p -lman'"
