# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec ~/.config/hypr/scripts/tmux-smart-attach.sh
bindd = SUPER SHIFT, RETURN, Terminal (no tmux), exec, uwsm-app -- xdg-terminal-exec
# bindd = SUPER ALT, F, FSearch, exec, fsearch
bindd = SUPER ALT, F, Search, exec, vicinae vicinae://extensions/vicinae/file/search
bindd = SUPER ALT, Y, File manager, exec, launch-tui-large yazi
bindd = SUPER ALT, M, MS Teams, exec, launch-or-focus teams-for-linux
bindd = SUPER ALT, B, Browser, exec, launch-or-focus brave-browser "uwsm app -- brave --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime"
bindd = SUPER ALT, N, Editor, exec, launch-editor
bindd = SUPER ALT, D, Docker, exec, launch-tui-large lazydocker
bindd = SUPER ALT, O, Obsidian, exec, launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER ALT, SLASH, Passwords, exec, uwsm app -- 1password
bindd = SUPER ALT, G, GitKraken, exec, launch-or-focus gitkraken "uwsm app -- gitkraken"
bindd = SUPER ALT, S, Signal, exec, launch-or-focus signal "uwsm app -- signal-desktop"
bindd = SUPER ALT, P, 1Password, exec, launch-or-focus 1password "uwsm app -- 1password"
