$terminal = uwsm app -- $TERMINAL
# Menus
bindd = SUPER, SPACE, Dashboard, exec, vicinae toggle
bindd = SUPER CTRL, C, Capture menu, exec, menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, menu toggle
bindd = SUPER ALT, SPACE, Omarchy menu, exec, menu
bindd = SUPER, ESCAPE, System menu, exec, menu system
bindd = , XF86PowerOff, Power menu, exec, vicinae vicinae://launch/power
bindd = SUPER CTRL, K, Show key bindings, exec, menu-keybindings
bindd = , XF86Calculator, Calculator, exec, vicinae vicinae://extensions/vicinae/calculator/history
bindd = SUPER CTRL, W, Reload Waybar, exec, pkill waybar && waybar &
bindd = SUPER CTRL, H, Reload Hyprland, exec, restart-hyprctl

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, toggle-waybar
bindd = SUPER CTRL, SPACE, Theme background menu, exec, menu background
bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, hyprland-window-gaps-toggle
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, hyprland-window-single-square-aspect-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Pacman
bindd = SUPER CTRL, I, Install packages, exec, launch-tui-large pkg-install
bindd = SUPER CTRL, U, Update system, exec, launch-tui-large update
bindd = SUPER CTRL, R, Remove packages, exec, launch-tui-large pkg-remove
bindd = SUPER CTRL, A, Install AUR packages, exec, launch-tui-large pkg-aur-search

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec, brightness-display-apple -5000
bindd = CTRL, F2, Apple Display brightness up, exec, brightness-display-apple +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec, brightness-display-apple +60000

# Captures
bindd = , PRINT, Screenshot, exec, cmd-screenshot
bindd = ALT, PRINT, Screenrecording, exec, menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# File sharing
# bindd = SUPER CTRL, S, Share, exec, menu share

# Control panels
# bindd = SUPER CTRL, S, Audio controls, exec, launch-audio
# bindd = SUPER CTRL, B, Bluetooth controls, exec, launch-bluetooth
# bindd = SUPER CTRL, W, Wifi controls, exec, launch-wifi
bindd = SUPER CTRL, T, Top, exec, launch-tui btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, lock-screen

bindd = SUPER, V, Clipboard history, exec, vicinae vicinae://extensions/vicinae/clipboard/history
bindd = SUPER, PERIOD, Emoji picker, exec, vicinae vicinae://extensions/vicinae/core/search-emojis
