[Service]
Environment="WAYLAND_DISPLAY=wayland-1"
Environment="XDG_RUNTIME_DIR=/run/user/155801123"
Environment="DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/155801123/bus"
Environment="XDG_SESSION_TYPE=wayland"
