#!/bin/bash

set -Eeuo pipefail

MKINITCPIO_CONF="/etc/mkinitcpio.conf.d/resume.conf"

# Check if hibernation is supported
if [[ ! -f /sys/power/image_size ]]; then
  exit 1
fi

# Sum all swap sizes (excluding zram)
SWAPSIZE_KB=$(awk '!/Filename|zram/ {sum += $3} END {print sum+0}' /proc/swaps)
SWAPSIZE=$(( 1024 * ${SWAPSIZE_KB:-0} ))

HIBERNATION_IMAGE_SIZE=$(cat /sys/power/image_size)

if (( SWAPSIZE > HIBERNATION_IMAGE_SIZE )) && [[ -f $MKINITCPIO_CONF ]]; then
  exit 0
else
  exit 1
fi
