#!/bin/bash

# Close all open windows
hyprctl clients -j | \
  jq -r ".[].address" | \
  xargs -I{} hyprctl eval 'hl.dispatch(hl.dsp.window.close({window="address:{}"}))'

# Move to first workspace
hyprctl eval 'hl.dispatch(hl.dsp.focus({workspace=1}))'
