#!/bin/bash

# Launch the TUI command passed in as an argument in the default terminal at 90% monitor size.

exec setsid uwsm-app -- xdg-terminal-exec --app-id=org.float-large.$(basename $1) -e "$1" "${@:2}"
