#!/bin/bash

# Locks the system using hyprlock and ensures 1password has also been locked.

# Lock the screen
pidof hyprlock || hyprlock &

# Set keyboard layout to default (first layout)
hyprctl switchxkblayout all 0 > /dev/null 2>&1

# Ensure 1password is locked
if pgrep -x "1password" >/dev/null; then
  1password --lock &
fi
