#!/bin/bash

# Overwrite the user configs for the Waybar menu bar with the Omarchy defaults and restart the service.

refresh-config waybar/config.jsonc
refresh-config waybar/style.css
restart-waybar
