#!/bin/bash
set -e

# Reinstall the Omarchy configuration directory from the git source.

git clone "https://github.com/basecamp/omarchy.git" ~/.local/share/new >/dev/null
mv $OMARCHY_PATH ~/.local/share/old
mv ~/.local/share/new $OMARCHY_PATH
