#!/bin/bash

# Display a "Done!" message and wait for user to press any key.
# Used by various install scripts to indicate completion.

echo
if [[ -t 0 ]]; then
  read -n 1 -s -r -p "Done! Press any key to close..." || true
  echo
fi
