#!/bin/bash
set -Eeuo pipefail

# Install voxtype and configure it for use.

if gum confirm "Install Voxtype + AI model (~150MB) to enable dictation?"; then
  pkg-add wtype voxtype-bin

  voxtype setup --download
  voxtype setup systemd

  restart-waybar
  notify-send "    Voxtype Dictation Ready" "Press Super + Ctrl + X to toggle dictation.\nEdit ~/.config/voxtype/config.toml for options." -t 10000
fi
