-- App-specific tweaks
require("apps.1password")
require("apps.bitwarden")
require("apps.browser")
require("apps.hyprshot")
require("apps.jetbrains")
require("apps.localsend")
require("apps.mdexplorer")
require("apps.pip")
require("apps.qemu")
require("apps.retroarch")
require("apps.steam")
require("apps.geforce")
require("apps.moonlight")
require("apps.system")
require("apps.telegram")
require("apps.terminals")
require("apps.webcam-overlay")
